### ISSUE TITLE
Show password dialog at startup

### ISSUE THREAD

**Issue by mwiesweg** [veaceslav/TumorProfil#3]
With an available db connection (like from a master config file in the previous issue), start up to go straight to a username / password enter dialog.
Username can be stored locally for convenience. Password shall not be stored for now (must be reentered each time)

**Comment by veaceslav** [comment]
Just to clarify: username/password dialog for database user?(tumoruser?) 
And after that, the next username and password for encryption?

**Comment by mwiesweg** [comment]
The encryption design is complex, and I am not fully convinced that I am aware of all the details, so please correct me.

I have enough admin privileges on my SQL account to create database users. And I expect to have one database user per real person. 

TumorUsers encrypts the encryption key per-user in a table with the personal password, right?
I thought the user name used there was always equal to the db user name.
The password could be the same?
I agree that the function for a user to change his personal password might not be possible in that case, due to missing db write privileges.

**Comment by veaceslav** [comment]
If you have the root access it should be much easier.

For now, you will need to add user with a SQL statement(create user ...) and also add it with TumorUsers app in the database. Later I think I can change TumorUsers to execute the create user by itself, if you give it the root account.

Without knowing I implemented the second password enter dialog, but I think it should be easy to use the same username and password. I will come back when I will have something working.

Also, there might be an issue with #4 since it not only changes own password, the user also need to update encryption keys....

**Comment by veaceslav** [comment]
So I implemented the unified login. I am only left to implement mysql user add in TumorUser, so you will not have to do it manually.

**Comment by veaceslav** [comment]
Mysql user add/delete/grant permissions implemented in TumorUsers
