### ISSUE TITLE
Conversion script cuts PathologyProperties

### ISSUE THREAD

**Issue by mwiesweg** [veaceslav/TumorProfil#6]
When running the conversion script, only one single PathologyProperty entry for each Pathology is entered into the database.
I did not check if the other ...Properties tables work correctly; there's usually only a single entry at the moment.

**Comment by veaceslav** [comment]
The script is unable to create tables correctly. Specifically after it creates them, they miss some parameters such as UNIQUE.

I wrote in readme file that first tumorProfil should create all databases then, the import should be performed with the script. If you followed the exact instructions and the problem is still here, then I will investigate.

**Comment by mwiesweg** [comment]
Yes, I just reproduced:
Created databases in mysql; run Tumorprofil to create tables, verified; run 
conversion script. -> Only one entry for each patient in the 
PathologyProperties table.

Marcel

**Comment by veaceslav** [comment]
FIXED. The problem was that for mySQL tumorProfil was creating the PathologyProperties with PRIMARY KEY AUTO INCREMENT. My bad. I guess I was not careful enough when porting the sqlite to mysql. Also, if you want to check the statements in dbconfig,xml. 

Please delete tumorprofil database initialize all tables with tumorProfil and run conversion script again
